### ISSUE TITLE
Extra line in highlighted code blocks on Firefox

### ISSUE THREAD

**Issue by franky47** [j0lv3r4/mdx-prism#4]
I have a weird issue. On Firefox (not Chrome nor Safari), and only in code blocks with highlighted lines, there is an extra empty line at the end of the code block:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/1174092/83946420-0cbf5e80-a811-11ea-97b3-2c0d55849b3f.png">

On Chrome and Safari the extra line is not present:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/1174092/83946499-9707c280-a811-11ea-828f-607f8d597967.png">

Here's a URL where I have demo code blocks:
https://francoisbest.com/design-system#code-blocks

The issue does not appear on your blog. The main difference I could find is that you invoke `mdx-prism` in a rehype pipeline, while I use it as a rehype plugin in `next-mdx-enhanced` ([source](https://github.com/franky47/francoisbest.com/blob/72be75168798e723297489442915238d43eaefd6/next.config.js#L44)).

The output HTML (not seen as parsed from the devtools, but raw from _View Source_) shows differences in whitespace and formatting, which could explain the issue, however there are no differences from the last `}` in the code snippet until the closing `</pre>` tag:
- [jolvera.txt](https://github.com/j0lv3r4/mdx-prism/files/4740458/jolvera.txt)
- [francoisbest.txt](https://github.com/j0lv3r4/mdx-prism/files/4740460/francoisbest.txt)

FIY, @leerob's [blog](https://leerob.io/blog/mdx#better-syntax-highlighting), which led me to this fork, has the same issue.

Context:
- Next.js v9.4.4
- `next-mdx-enhanced` v3.0.0
- `mdx-prism` v0.3.1
- `rehyme` v10.0.0 (same issue with v9.0.0 as used in your blog)

**Comment by j0lv3r4** [comment]
I remember having this issue, but I totally forgot how to fix it :thinking:.

I will go through my git history, find out what I did, and ping you back with a solution.

**Comment by franky47** [comment]
Thanks, I really appreciate your effort!

**Comment by j0lv3r4** [comment]
Found it! Well... I didn't found it, I debugged the issue because my git comments suck :man_facepalming:.

To your `pre` elements add ` white-space: nowrap;`

![image](https://user-images.githubusercontent.com/1130549/84078013-cd724880-a99d-11ea-9876-cbdac68ebf79.png)

![image](https://user-images.githubusercontent.com/1130549/84077878-956b0580-a99d-11ea-8a67-3653403cf390.png)

I added `!important` as a quick fix, but you can manage to add that without it in any way you see convenient.

`mdx-prism` probably adds whitespace or a break line in the last element. I will debug the issue and submit a patch soon. But adding `white-space: nowrap;` should fix it for now.

**Comment by franky47** [comment]
Yes, that worked!
```css
code {
  white-space: pre;
}
pre {
  white-space: nowrap;
}
```

Thanks a lot 🙌
